version: '3.8'

services:
  backoffice-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automo-backoffice
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      DEBUG_MODE: ${DEBUG_MODE:-true}
      BASE_URL: ${BASE_URL:-http://localhost:3000}
      API_BASE_URL: ${API_BASE_URL:-http://automo-app:8080}  # Connect via container name
      PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS:-On}
      PHP_ERROR_REPORTING: ${PHP_ERROR_REPORTING:-E_ALL}
      PHP_LOG_ERRORS: ${PHP_LOG_ERRORS:-On}
    volumes:
      - ./storage/logs:/var/www/html/storage/logs
      - ./public/uploads:/var/www/html/public/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      - cache

  cache:
    image: redis:7-alpine
    container_name: automo-backoffice-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: automo-backoffice-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/html/public:ro
    depends_on:
      - backoffice-app
    profiles:
      - production

volumes:
  cache_data:
    driver: local

networks:
  default:
    name: automo-network
    external: true