version: '3.8'

services:
  backoffice-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automo-backoffice-prod
    restart: unless-stopped
    environment:
      # Application Configuration
      DEBUG_MODE: false
      BASE_URL: ${BASE_URL:-https://your-domain.com}
      
      # Backend API Configuration (Production)
      API_BASE_URL: ${API_BASE_URL:-https://your-backend-domain.com}
      
      # PHP Configuration (Production)
      PHP_DISPLAY_ERRORS: Off
      PHP_ERROR_REPORTING: E_ERROR
      PHP_LOG_ERRORS: On
      
    volumes:
      - ./storage/logs:/var/www/html/storage/logs
      - ./public/uploads:/var/www/html/public/uploads
      - ./storage/sessions:/var/www/html/storage/sessions
    networks:
      - backoffice-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
  # Nginx for SSL termination and reverse proxy
  nginx:
    image: nginx:alpine
    container_name: automo-backoffice-nginx-prod
    restart: unless-stopped
    ports:
      - "443:443"  # HTTPS
      - "80:80"     # HTTP redirect
    volumes:
      - ./docker/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro  # SSL certificates
      - ./public:/var/www/html/public:ro
    depends_on:
      - backoffice-app
    networks:
      - backoffice-network

networks:
  backoffice-network:
    driver: bridge